export const macrocycleSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "summary",
    "seasonObjective",
    "periodizationRationale",
    "totalWeeks",
    "totalSessions",
    "totalMinutes",
    "periods",
    "annualLoadSummary",
    "mainCompetitionGuidance",
    "evaluationCriteria",
    "safetyMeasures",
    "adaptationNotes",
  ],
  properties: {
    title: { type: "string" },
    summary: { type: "string" },
    seasonObjective: { type: "string" },
    periodizationRationale: { type: "string" },
    totalWeeks: { type: "integer" },
    totalSessions: { type: "integer" },
    totalMinutes: { type: "integer" },
    periods: {
      type: "array",
      minItems: 3,
      maxItems: 3,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "periodNumber",
          "type",
          "title",
          "weekStart",
          "weekEnd",
          "objective",
          "focus",
          "intensity",
          "loadLevel",
          "sessionCount",
          "totalMinutes",
          "organization",
          "keyContents",
          "progression",
          "recovery",
          "monitoring",
          "safety",
        ],
        properties: {
          periodNumber: { type: "integer" },
          type: {
            type: "string",
            enum: ["preparatory", "competitive", "transition"],
          },
          title: { type: "string" },
          weekStart: { type: "integer" },
          weekEnd: { type: "integer" },
          objective: { type: "string" },
          focus: {
            type: "string",
            enum: [
              "technical",
              "tactical",
              "physical",
              "coordination",
              "recovery",
              "combined",
            ],
          },
          intensity: {
            type: "string",
            enum: ["low", "moderate", "high-controlled"],
          },
          loadLevel: { type: "integer", minimum: 1, maximum: 5 },
          sessionCount: { type: "integer" },
          totalMinutes: { type: "integer" },
          organization: { type: "string" },
          keyContents: {
            type: "array",
            minItems: 3,
            maxItems: 5,
            items: { type: "string" },
          },
          progression: { type: "string" },
          recovery: { type: "string" },
          monitoring: { type: "string" },
          safety: { type: "string" },
        },
      },
    },
    annualLoadSummary: { type: "string" },
    mainCompetitionGuidance: { type: "string" },
    evaluationCriteria: {
      type: "array",
      description:
        'Cuatro criterios diferentes. Cada uno comienza con "Evidencia observable:", incluye un verbo de acción observable y un indicador verificable o una relación numérica.',
      minItems: 4,
      maxItems: 4,
      items: {
        type: "string",
        description:
          'Formato: "Evidencia observable: ejecuta [conducta] en [condición] con [indicador verificable]".',
      },
    },
    safetyMeasures: {
      type: "array",
      minItems: 3,
      maxItems: 5,
      items: { type: "string" },
    },
    adaptationNotes: {
      type: "array",
      minItems: 3,
      maxItems: 5,
      items: { type: "string" },
    },
  },
} as const;
