export const mesocycleSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "summary",
    "mainObjective",
    "phaseGuidance",
    "totalWeeks",
    "totalSessions",
    "totalMinutes",
    "weeks",
    "overallLoadSummary",
    "evaluationCriteria",
    "safetyMeasures",
    "adaptationNotes",
  ],
  properties: {
    title: { type: "string" },
    summary: { type: "string" },
    mainObjective: { type: "string" },
    phaseGuidance: { type: "string" },
    totalWeeks: { type: "integer" },
    totalSessions: { type: "integer" },
    totalMinutes: { type: "integer" },
    weeks: {
      type: "array",
      minItems: 3,
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "weekNumber",
          "title",
          "objective",
          "focus",
          "intensity",
          "loadLevel",
          "sessionCount",
          "sessionDurationMinutes",
          "totalMinutes",
          "organization",
          "keyContents",
          "loadGuidance",
          "recovery",
          "monitoring",
          "safety",
        ],
        properties: {
          weekNumber: { type: "integer" },
          title: { type: "string" },
          objective: { type: "string" },
          focus: {
            type: "string",
            enum: [
              "technical",
              "tactical",
              "physical",
              "coordination",
              "recovery",
              "combined",
            ],
          },
          intensity: {
            type: "string",
            enum: ["low", "moderate", "high-controlled"],
          },
          loadLevel: { type: "integer", minimum: 1, maximum: 5 },
          sessionCount: { type: "integer" },
          sessionDurationMinutes: { type: "integer" },
          totalMinutes: { type: "integer" },
          organization: { type: "string" },
          keyContents: {
            type: "array",
            minItems: 3,
            maxItems: 5,
            items: { type: "string" },
          },
          loadGuidance: { type: "string" },
          recovery: { type: "string" },
          monitoring: { type: "string" },
          safety: { type: "string" },
        },
      },
    },
    overallLoadSummary: { type: "string" },
    evaluationCriteria: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: { type: "string" },
    },
    safetyMeasures: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: { type: "string" },
    },
    adaptationNotes: {
      type: "array",
      minItems: 2,
      maxItems: 5,
      items: { type: "string" },
    },
  },
} as const;
