export const microcycleSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "summary",
    "weeklyObjective",
    "phaseGuidance",
    "totalSessions",
    "totalMinutes",
    "days",
    "weeklyLoadSummary",
    "evaluationCriteria",
    "safetyMeasures",
    "adaptationNotes",
  ],
  properties: {
    title: { type: "string" },
    summary: { type: "string" },
    weeklyObjective: { type: "string" },
    phaseGuidance: { type: "string" },
    totalSessions: { type: "integer" },
    totalMinutes: { type: "integer" },
    days: {
      type: "array",
      minItems: 2,
      maxItems: 7,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "day",
          "sessionNumber",
          "title",
          "objective",
          "focus",
          "intensity",
          "minutes",
          "loadLevel",
          "organization",
          "segments",
          "coachingPoints",
          "recovery",
          "monitoring",
          "safety",
        ],
        properties: {
          day: {
            type: "string",
            enum: [
              "monday",
              "tuesday",
              "wednesday",
              "thursday",
              "friday",
              "saturday",
              "sunday",
            ],
          },
          sessionNumber: { type: "integer" },
          title: { type: "string" },
          objective: { type: "string" },
          focus: {
            type: "string",
            enum: [
              "technical",
              "tactical",
              "physical",
              "coordination",
              "recovery",
              "combined",
            ],
          },
          intensity: {
            type: "string",
            enum: ["low", "moderate", "high-controlled"],
          },
          minutes: { type: "integer" },
          loadLevel: {
            type: "integer",
            minimum: 1,
            maximum: 5,
          },
          organization: { type: "string" },
          segments: {
            type: "array",
            minItems: 3,
            maxItems: 5,
            items: {
              type: "object",
              additionalProperties: false,
              required: ["name", "minutes", "objective", "content"],
              properties: {
                name: { type: "string" },
                minutes: { type: "integer" },
                objective: { type: "string" },
                content: { type: "string" },
              },
            },
          },
          coachingPoints: {
            type: "array",
            minItems: 2,
            maxItems: 5,
            items: { type: "string" },
          },
          recovery: { type: "string" },
          monitoring: { type: "string" },
          safety: { type: "string" },
        },
      },
    },
    weeklyLoadSummary: { type: "string" },
    evaluationCriteria: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: { type: "string" },
    },
    safetyMeasures: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: { type: "string" },
    },
    adaptationNotes: {
      type: "array",
      minItems: 2,
      maxItems: 5,
      items: { type: "string" },
    },
  },
} as const;
