export const trainingSessionSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "summary",
    "objective",
    "totalMinutes",
    "loadGuidance",
    "blocks",
    "evaluationCriteria",
    "safetyMeasures",
    "adaptationNotes",
  ],
  properties: {
    title: { type: "string" },
    summary: { type: "string" },
    objective: { type: "string" },
    totalMinutes: { type: "integer" },
    loadGuidance: { type: "string" },
    blocks: {
      type: "array",
      minItems: 4,
      maxItems: 6,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "name",
          "objective",
          "minutes",
          "intensity",
          "organization",
          "activities",
          "coachingPoints",
          "recovery",
          "safety",
        ],
        properties: {
          name: { type: "string" },
          objective: { type: "string" },
          minutes: { type: "integer" },
          intensity: { type: "string" },
          organization: { type: "string" },
          activities: {
            type: "array",
            minItems: 1,
            maxItems: 5,
            items: {
              type: "object",
              additionalProperties: false,
              required: [
                "name",
                "minutes",
                "description",
                "segments",
              ],
              properties: {
                name: { type: "string" },
                minutes: { type: "integer" },
                description: { type: "string" },
                segments: {
                  type: "array",
                  minItems: 1,
                  maxItems: 12,
                  items: {
                    type: "object",
                    additionalProperties: false,
                    required: [
                      "name",
                      "seconds",
                      "description",
                    ],
                    properties: {
                      name: { type: "string" },
                      seconds: {
                        type: "integer",
                        minimum: 1,
                      },
                      description: { type: "string" },
                    },
                  },
                },
              },
            },
          },
          coachingPoints: {
            type: "array",
            minItems: 1,
            maxItems: 5,
            items: { type: "string" },
          },
          recovery: { type: "string" },
          safety: { type: "string" },
        },
      },
    },
    evaluationCriteria: {
      type: "array",
      minItems: 2,
      maxItems: 6,
      items: { type: "string" },
    },
    safetyMeasures: {
      type: "array",
      minItems: 3,
      maxItems: 7,
      items: { type: "string" },
    },
    adaptationNotes: {
      type: "array",
      minItems: 2,
      maxItems: 5,
      items: { type: "string" },
    },
  },
} as const;
