export type SchoolLevel = "Preparatoria" | "EGB Elemental" | "EGB Media" | "EGB Superior" | "BGU";

export interface HealthyLesson {
  id: string;
  module: string;
  title: string;
  subtitle: string;
  icon: string;
  purpose: string;
  keyPoints: [string, string, string];
  activity: string;
  evidence: string;
  safety: string;
  family: string;
  source: "OMS" | "FAO" | "MSP Ecuador" | "UNICEF";
}

const lesson = (
  id: string, module: string, title: string, subtitle: string, icon: string,
  purpose: string, keyPoints: [string, string, string], activity: string,
  evidence: string, safety: string, family: string,
  source: HealthyLesson["source"] = "OMS",
): HealthyLesson => ({ id, module, title, subtitle, icon, purpose, keyPoints, activity, evidence, safety, family, source });

export const healthyLessons: HealthyLesson[] = [
  lesson("plato-flexible","Fundamentos","Plato saludable flexible","Variedad, cultura y disponibilidad","🥗","Reconocer una combinación variada sin imponer una dieta única.",["Incluye frutas y verduras variadas.","Combina fuentes de energía y proteína.","El agua es la bebida habitual."],"Construyan platos con tarjetas de alimentos locales y expliquen sus elecciones.","Explica dos razones de su combinación.","No clasificar platos familiares como buenos o malos.","Identifiquen una combinación habitual que puedan enriquecer.","FAO"),
  lesson("macronutrientes","Fundamentos","Macronutrientes","Energía, estructura y funciones","🌾","Diferenciar funciones generales sin contar calorías.",["Los carbohidratos aportan energía.","Las proteínas participan en crecimiento y reparación.","Las grasas cumplen funciones esenciales."],"Relacionen alimentos cotidianos con sus funciones mediante estaciones.","Clasifica ejemplos y justifica uno.","Evitar mensajes de eliminación de grupos alimentarios.","Busquen una comida que combine los tres grupos.","FAO"),
  lesson("micronutrientes","Fundamentos","Vitaminas y minerales","La variedad ayuda a cubrir necesidades","🌈","Comprender por qué conviene variar los alimentos.",["Ningún color aporta por sí solo todo lo necesario.","La variedad es más importante que un alimento milagroso.","Los suplementos requieren orientación profesional."],"Completen un arcoíris con tarjetas, dibujos o descripciones.","Propone tres colores y sus alimentos.","No atribuir curas o defensas garantizadas a un alimento.","Observen cuántos colores aparecen en una comida familiar.","OMS"),
  lesson("guias-ecuador","Fundamentos","Guías alimentarias de Ecuador","Mensajes para una alimentación pertinente","🇪🇨","Relacionar recomendaciones con alimentos y costumbres ecuatorianas.",["Prioriza alimentos naturales o mínimamente procesados.","Valora preparaciones y productos locales.","Adapta las elecciones a disponibilidad y cultura."],"Elaboren un mapa de alimentos de su región.","Presenta una elección local y accesible.","Evitar ridiculizar costumbres o posibilidades económicas.","Recuperen una preparación tradicional de la familia.","MSP Ecuador"),
  lesson("hidratacion-escolar","Hidratación y movimiento","Hidratación escolar","Acceso al agua antes, durante y después","💧","Planificar oportunidades de hidratación sin fórmulas universales.",["Las necesidades varían entre personas y condiciones.","Debe haber acceso regular a agua segura.","El calor y la actividad exigen mayor atención."],"Diseñen señales y pausas de agua para una clase de 45 minutos.","Propone un protocolo viable.","No restringir el agua ni prescribir cantidades individuales.","Preparen una botella identificada cuando la institución lo permita.","OMS"),
  lesson("calor-movimiento","Hidratación y movimiento","Actividad física y calor","Pausas, sombra y observación","☀️","Reconocer condiciones que requieren adaptar la clase.",["Ajusta intensidad y duración al ambiente.","Programa pausas y acceso a sombra.","Detén la actividad ante malestar."],"Analicen tres escenarios climáticos y decidan cómo adaptar la sesión.","Justifica una modificación segura.","Suspender ante mareo, confusión, dolor o dificultad respiratoria.","Conversen sobre lugares frescos y agua segura cercanos.","OMS"),
  lesson("bebidas","Hidratación y movimiento","Agua y otras bebidas","Lectura crítica sin prohibiciones","🥤","Comparar bebidas mediante información verificable.",["El agua es la opción habitual de hidratación.","Las bebidas azucaradas pueden aportar mucho azúcar libre.","Una etiqueta debe leerse por porción y producto."],"Comparen etiquetas ficticias de tres bebidas.","Selecciona información relevante sin moralizar.","No realizar degustaciones sin autorización y revisión de alergias.","Comparen una bebida habitual con agua o una alternativa sin azúcar añadida.","OMS"),
  lesson("alrededor-actividad","Hidratación y movimiento","Antes y después de moverse","Comodidad, hidratación y recuperación cotidiana","🍌","Tomar decisiones prudentes alrededor de la actividad física.",["No existe un alimento único obligatorio.","La tolerancia, el tiempo y el contexto importan.","Agua, alimentación habitual y descanso apoyan la recuperación."],"Resuelvan casos sobre horarios, alimentos familiares, hidratación y descanso.","Elige una opción y explica el contexto.","No recomendar suplementos, cantidades universales ni dietas individualizadas.","Identifiquen opciones sencillas disponibles antes o después de una jornada activa.","FAO"),
  lesson("lonchera","Entorno escolar","Lonchera posible y variada","Sin concursos ni comparaciones","🎒","Diseñar opciones considerando seguridad, costo y cultura.",["Combina alimentos disponibles y agua.","La variedad puede lograrse de muchas maneras.","La conservación segura es indispensable."],"Diseñen loncheras ficticias para contextos diferentes.","Explica variedad, seguridad y viabilidad.","No fotografiar ni calificar loncheras reales del alumnado.","Revisen una opción económica y posible para su hogar.","FAO"),
  lesson("desayuno","Entorno escolar","Desayunos diversos","Rutinas sin culpabilizar","🌅","Explorar opciones realistas según los hogares.",["Las rutinas familiares son diversas.","Una combinación variada puede adoptar muchas formas.","No desayunar no debe ser motivo de exposición o castigo."],"Creen tarjetas de desayunos locales para diferentes tiempos y recursos.","Propone una alternativa respetuosa.","Derivar situaciones de inseguridad alimentaria por canales institucionales.","Conversen sobre una opción disponible y agradable.","FAO"),
  lesson("refrigerio","Entorno escolar","Refrigerios y colaciones","Elecciones según hambre y jornada","🍎","Distinguir una colación útil de una obligación universal.",["El hambre y la duración de la jornada importan.","Frutas, cereales o proteínas pueden combinarse.","Las porciones dependen del contexto individual."],"Resuelvan casos de jornadas cortas, largas y con actividad.","Justifica cuándo y por qué incluir una colación.","No indicar porciones clínicas ni restringir alimentos.","Identifiquen opciones accesibles en su comunidad.","FAO"),
  lesson("seguridad-alimentaria","Entorno escolar","Seguridad alimentaria","Higiene, conservación y alergias","🧼","Aplicar condiciones seguras antes de manipular alimentos.",["Lava manos, superficies y utensilios.","Evita contaminación cruzada.","Confirma alergias, autorización y conservación."],"Ordenen un protocolo de preparación segura.","Detecta riesgos en un caso práctico.","Toda preparación requiere supervisión y autorización institucional.","Revisen cómo conservan los alimentos que llevan fuera de casa.","OMS"),
  lesson("acceso-alimentos","Entorno escolar","Acceso y realidad familiar","Aprender sin avergonzar","🤝","Reconocer que las elecciones dependen también del entorno.",["El acceso económico y geográfico condiciona opciones.","La escuela no debe culpabilizar a las familias.","Las soluciones deben ser posibles y culturalmente pertinentes."],"Comparen soluciones para distintos presupuestos sin usar datos personales.","Propone una alternativa accesible.","Comunicar necesidades alimentarias mediante protocolos de protección.","Identifiquen recursos comunitarios sin señalar a ninguna familia.","UNICEF"),
  lesson("semaforo","Etiquetas y pensamiento crítico","Semáforo nutricional","Alto, medio o bajo no significa dieta completa","🚦","Interpretar azúcar, grasa y sal sin clasificar personas ni alimentos.",["El semáforo informa nutrientes específicos.","Se comparan productos semejantes y porciones.","No reemplaza la lectura de ingredientes ni el contexto."],"Comparen dos etiquetas ficticias del mismo tipo de producto.","Explica qué informa y qué no informa.","No convertir los colores en castigos o permisos absolutos.","Revisen juntos una etiqueta sin juzgar a quien consume el producto.","MSP Ecuador"),
  lesson("ingredientes","Etiquetas y pensamiento crítico","Lista de ingredientes","Orden y nombres frecuentes","🔎","Identificar información básica de una etiqueta.",["Los ingredientes suelen aparecer en orden decreciente.","Un mismo componente puede tener distintos nombres.","La etiqueta debe leerse junto con la porción."],"Detecten ingredientes en etiquetas simuladas.","Localiza y explica tres datos.","Utilizar ejemplos ficticios o anonimizados.","Comparen dos productos semejantes disponibles en casa.","OMS"),
  lesson("publicidad","Etiquetas y pensamiento crítico","Publicidad alimentaria","Distinguir evidencia de persuasión","📺","Analizar técnicas de mercadeo dirigidas a niños y jóvenes.",["Personajes y promociones buscan influir.","Una afirmación atractiva necesita contexto.","La etiqueta ofrece datos distintos a la publicidad."],"Creen un contraanuncio que informe sin ridiculizar.","Identifica dos técnicas persuasivas.","No exhibir elecciones personales del alumnado.","Conversen sobre un anuncio y qué información omite.","UNICEF"),
  lesson("ultraprocesados","Etiquetas y pensamiento crítico","Grado de procesamiento","Frecuencia y contexto","📦","Diferenciar alimentos frescos, procesados y ultraprocesados sin alarmismo.",["Procesar no convierte automáticamente un alimento en dañino.","Conviene priorizar variedad y alimentos poco procesados.","La frecuencia y el patrón general importan."],"Ordenen tarjetas y debatan casos fronterizos.","Clasifica justificando, sin usar buenos o malos.","Evitar mensajes de miedo, culpa o pureza alimentaria.","Identifiquen una preparación casera posible.","FAO"),
  lesson("mitos","Etiquetas y pensamiento crítico","Mitos de nutrición y deporte","Buscar evidencia antes de compartir","🧠","Cuestionar promesas rápidas y productos milagro.",["Un testimonio no demuestra eficacia.","Natural no significa siempre seguro.","Los suplementos requieren valoración profesional."],"Realicen un juicio al mensaje, no a la persona.","Separa dato, opinión y publicidad.","No experimentar con suplementos o restricciones.","Busquen quién firma una afirmación nutricional.","OMS"),
  lesson("imagen-corporal","Bienestar y convivencia","Diversidad corporal","Respeto, privacidad y participación","💛","Promover un entorno sin burlas ni comparaciones.",["Los cuerpos crecen y cambian de formas diversas.","El valor personal no depende del peso o la apariencia.","La evaluación física debe proteger la privacidad."],"Construyan acuerdos de lenguaje respetuoso.","Propone una acción contra la estigmatización.","No pesar, medir ni comparar cuerpos en esta actividad.","Reconozcan cualidades no relacionadas con la apariencia.","UNICEF"),
  lesson("relacion-alimentos","Bienestar y convivencia","Relación respetuosa con la comida","Sin culpa, premio ni castigo","🫶","Evitar moralizar la alimentación.",["Comer no determina el valor de una persona.","Los alimentos no deben utilizarse como castigo.","Una dificultad persistente requiere apoyo, no juicio."],"Reescriban frases culpabilizantes con lenguaje respetuoso.","Transforma tres mensajes.","No pedir confesiones ni registros personales.","Identifiquen frases familiares que puedan decirse con más respeto.","UNICEF"),
  lesson("senales-alerta","Bienestar y convivencia","Señales de alerta","Observar, escuchar y derivar","🧭","Reconocer cuándo corresponde activar apoyo profesional.",["El docente no diagnostica trastornos alimentarios.","Cambios preocupantes requieren conversación privada y protocolo.","La derivación incluye familia, orientación y salud según el caso."],"Analicen un caso ficticio y ordenen la ruta de apoyo.","Distingue acompañar de diagnosticar.","Ante riesgo inmediato, activar el protocolo institucional.","Conozcan a qué adulto o servicio seguro acudir.","OMS"),
  lesson("alimentacion-consciente","Bienestar y convivencia","Atención al comer","Curiosidad sin competencia","🧘","Explorar señales y sentidos sin imponer resultados.",["La atención puede practicarse sin degustar.","No todas las personas perciben igual hambre o saciedad.","La experiencia no debe convertirse en competencia."],"Describan una imagen de alimento mediante sentidos imaginados.","Registra observaciones sin calificarlas.","No usar vendas ni alimentos reales sin protocolo y consentimiento.","Prueben una pausa tranquila si resulta cómoda.","OMS"),
  lesson("sueño-rutinas","Bienestar y convivencia","Sueño, rutinas y bienestar","La salud no depende de una sola elección","🌙","Relacionar hábitos sin promesas deterministas.",["El descanso apoya el bienestar y la participación.","Las rutinas pueden adaptarse gradualmente.","Una noche o comida no define la salud."],"Construyan una rueda de hábitos posibles.","Elige una mejora alcanzable y no corporal.","No evaluar circunstancias familiares fuera del control estudiantil.","Acuerden una rutina posible para una semana.","OMS"),
  lesson("receta-fria","Práctica docente","Experiencia culinaria sin cocción","Planificar antes de preparar","🥣","Diseñar una experiencia segura y opcional.",["La autorización y alergias se revisan primero.","La higiene y conservación forman parte del aprendizaje.","Debe existir una alternativa sin degustación."],"Planifiquen una preparación fría con roles cooperativos.","Entrega una lista de verificación segura.","Supervisión adulta; utensilios seguros y sin contaminación cruzada.","Revisen ingredientes alternativos según el hogar.","FAO"),
  lesson("menu-flexible","Práctica docente","Menú escolar flexible","Planificar variedad, no prescribir dietas","📅","Organizar ejemplos educativos sin indicar tratamientos.",["Un menú es un ejemplo adaptable.","Debe considerar cultura, presupuesto y disponibilidad.","Las necesidades clínicas corresponden a profesionales."],"Diseñen un día ficticio y expliquen sus decisiones.","Justifica variedad y viabilidad.","No asignar dietas para perder peso o tratar enfermedades.","Propongan una sustitución local para un ingrediente.","FAO"),
  lesson("compras","Práctica docente","Compras informadas","Lista, presupuesto y comparación","🛒","Tomar decisiones realistas sin juzgar marcas o familias.",["Planificar puede reducir compras improvisadas.","Comparar productos semejantes aporta información.","Temporada y cercanía pueden mejorar disponibilidad."],"Resuelvan una compra ficticia con presupuesto limitado.","Argumenta prioridades y sustituciones.","No solicitar información económica personal.","Elaboren una lista breve para una preparación familiar.","FAO"),
  lesson("huerto","Práctica docente","Huerto y aprendizaje","Cuidar, observar y valorar alimentos","🌱","Relacionar cultivo, ambiente y alimentación.",["Cultivar ayuda a comprender procesos y temporadas.","Un huerto no sustituye el acceso alimentario.","Todas las tareas admiten formas equivalentes de participación."],"Diseñen roles accesibles para sembrar, registrar o comunicar.","Documenta un cambio observado.","Revisar herramientas, suelo, higiene y alergias ambientales.","Cultiven o investiguen una planta local.","FAO"),
  lesson("clase-45","Práctica docente","Clase activa de 45 minutos","Movimiento, análisis y reflexión","🏃","Construir una sesión educativa segura.",["Inicio: recuperar ideas sin exponer hábitos.","Desarrollo: resolver un reto cooperativo.","Cierre: obtener una evidencia breve."],"Seleccionen una lección y organicen 8-30-7 minutos.","Entrega objetivo, secuencia y evaluación.","Revisar espacio, hidratación, alergias y alternativas.","Compartan una pregunta de reflexión, no datos personales.","OMS"),
  lesson("dua-alimentacion","Práctica docente","DUA y alimentación","Varias formas de comprender y participar","🧩","Diseñar experiencias accesibles sin perder el objetivo.",["Representa con objetos, imágenes, audio o texto.","Permite responder hablando, dibujando, clasificando o escribiendo.","Ofrece elección y conexión cultural significativa."],"Rediseñen una actividad con los tres principios DUA.","Presenta tres apoyos equivalentes.","No obligar a tocar, oler, probar o revelar información.","Elijan la forma más cómoda de compartir un aprendizaje.","UNICEF"),
  lesson("evaluacion-formativa","Práctica docente","Evaluación formativa","Comprender, decidir y justificar","✅","Evaluar aprendizaje, no cuerpos ni comidas familiares.",["Los criterios deben ser observables.","La retroalimentación orienta el siguiente paso.","No se califican peso, apariencia o consumo personal."],"Construyan una rúbrica de cuatro niveles para analizar un caso.","Define tres criterios observables.","Usar ejemplos ficticios y proteger la privacidad.","Realicen una autoevaluación sobre lo aprendido.","FAO"),
];

export const levels: SchoolLevel[] = ["Preparatoria", "EGB Elemental", "EGB Media", "EGB Superior", "BGU"];

export const levelGuidance: Record<SchoolLevel, string> = {
  "Preparatoria": "Usa imágenes, relatos, clasificación simple y actividades de 5 a 8 minutos.",
  "EGB Elemental": "Prioriza ejemplos cotidianos, movimiento guiado y respuestas mediante dibujos o palabras breves.",
  "EGB Media": "Incorpora comparación, explicación oral y decisiones cooperativas con casos sencillos.",
  "EGB Superior": "Trabaja análisis de etiquetas, publicidad, contexto social y argumentación con evidencias.",
  "BGU": "Profundiza en fuentes, pensamiento crítico, diseño de campañas y evaluación de decisiones contextualizadas.",
};

export const sourceLinks: Record<HealthyLesson["source"], string> = {
  OMS: "https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
  FAO: "https://www.fao.org/nutrition/education/food-dietary-guidelines/home/en/",
  "MSP Ecuador": "https://www.salud.gob.ec/",
  UNICEF: "https://www.unicef.org/nutrition",
};
