"use client";

import { useMemo, useState } from "react";
import { inCheck, initialState, legalMoves, makeMove, squareName, type ChessState, type Move } from "@/features/students/chess/engine";

const symbols:Record<string,string>={wp:"♙",wn:"♘",wb:"♗",wr:"♖",wq:"♕",wk:"♔",bp:"♟",bn:"♞",bb:"♝",br:"♜",bq:"♛",bk:"♚"};
const sequences=[
 {title:"Primeros pasos — 45 minutos",items:["5 min: orientación del tablero y coordenadas","10 min: colocación colaborativa","15 min: peón, torre y alfil con microretos","10 min: caballo, dama y rey","5 min: salida de tres preguntas"]},
 {title:"Jaque y protección — 45 minutos",items:["7 min: recuperar movimientos","8 min: concepto de ataque y jaque","20 min: mover, capturar o bloquear","7 min: reto por parejas","3 min: reflexión"]},
 {title:"Reglas especiales — 45 minutos",items:["8 min: enroque con demostración","8 min: captura al paso","8 min: promoción elegible","15 min: posiciones de práctica","6 min: comprobación formativa"]},
];

export default function ChessTeacherApp(){
 const[state,setState]=useState<ChessState>(initialState),[history,setHistory]=useState<ChessState[]>([]),[selected,setSelected]=useState<number|null>(null),[flipped,setFlipped]=useState(false),[tab,setTab]=useState<"demo"|"challenge"|"plan">("demo"),[task,setTask]=useState("Encuentra el mejor movimiento y explica por qué."),[copied,setCopied]=useState(false);
 const moves=useMemo(()=>selected===null?[]:legalMoves(state,selected),[state,selected]);
 function choose(square:number){const piece=state.board[square];if(selected===null){if(piece?.color===state.turn)setSelected(square);return;}if(piece?.color===state.turn){setSelected(square);return;}const move=moves.find(x=>x.to===square);if(!move){setSelected(null);return;}const next=makeMove(state,move);if(next){setHistory(x=>[...x,state]);setState(next);setSelected(null)}}
 function undo(){const previous=history.at(-1);if(previous){setState(previous);setHistory(x=>x.slice(0,-1));setSelected(null)}}
 function share(){const payload=btoa(unescape(encodeURIComponent(JSON.stringify({board:state.board,turn:state.turn,task})))).slice(0,120);navigator.clipboard?.writeText(`AJEDREZ-${payload}`).then(()=>setCopied(true)).catch(()=>setCopied(false));}
 return <section className="space-y-6 rounded-[2rem] border border-amber-200 bg-white p-5 shadow-xl sm:p-8"><div className="rounded-3xl bg-gradient-to-br from-slate-950 to-amber-800 p-7 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">Herramienta docente Pro</p><h2 className="mt-2 text-3xl font-black">Ajedrez Educativo</h2><p className="mt-2 text-slate-200">Demuestra, guía, crea retos y organiza secuencias para la clase.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setTab("demo")} className={button(tab==="demo")}>♟ Demostración</button><button onClick={()=>setTab("challenge")} className={button(tab==="challenge")}>🎯 Crear reto</button><button onClick={()=>setTab("plan")} className={button(tab==="plan")}>📘 Secuencias</button></div>{tab!=="plan"?<div className="grid gap-6 xl:grid-cols-[minmax(420px,720px)_1fr]"><TeacherBoard state={state} selected={selected} moves={moves} choose={choose} flipped={flipped}/><aside className="space-y-4"><div className="rounded-2xl border p-5"><h3 className="text-xl font-black">Panel docente</h3><p className="mt-2 font-bold">Turno: {state.turn==="w"?"blancas":"negras"}{inCheck(state,state.turn)?" · Jaque":""}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>{setState(initialState());setHistory([])}} className="rounded-lg bg-slate-950 px-3 py-2 font-bold text-white">Posición inicial</button><button onClick={undo} disabled={!history.length} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Deshacer</button><button onClick={()=>setFlipped(x=>!x)} className="rounded-lg border px-3 py-2 font-bold">Girar tablero</button></div></div>{tab==="challenge"&&<div className="rounded-2xl border p-5"><label className="font-black">Consigna del reto<textarea value={task} onChange={e=>setTask(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3 font-normal"/></label><button onClick={share} className="mt-3 rounded-xl bg-amber-500 px-5 py-3 font-black text-slate-950">Copiar código del reto</button>{copied&&<p className="mt-2 text-sm font-bold text-emerald-700">Código copiado.</p>}<p className="mt-3 text-xs text-slate-500">El código no contiene nombres ni información estudiantil.</p></div>}</aside></div>:<div className="grid gap-5 lg:grid-cols-3">{sequences.map(sequence=><article key={sequence.title} className="rounded-2xl border p-5"><h3 className="text-xl font-black">{sequence.title}</h3><ol className="mt-4 space-y-3 text-sm leading-6">{sequence.items.map(item=><li key={item}>{item}</li>)}</ol></article>)}</div>}<div className="rounded-2xl bg-blue-50 p-5 text-sm leading-6 text-blue-950"><b>Seguimiento responsable:</b> el progreso individual pertenece al estudiante. La visualización docente por curso se habilitará cuando cada cuenta estudiantil pueda vincularse explícitamente con un docente, evitando mostrar registros de otros centros.</div></section>
}

function TeacherBoard({state,selected,moves,choose,flipped}:{state:ChessState;selected:number|null;moves:Move[];choose:(x:number)=>void;flipped:boolean}){const targets=new Set(moves.map(m=>m.to)),order=flipped?[...Array(64).keys()].reverse():[...Array(64).keys()];return <div className="grid max-w-[720px] grid-cols-8 overflow-hidden rounded-xl border-4 border-slate-950 shadow-2xl">{order.map(square=>{const piece=state.board[square],light=(Math.floor(square/8)+square%8)%2===0;return <button key={square} onClick={()=>choose(square)} aria-label={`${piece?symbols[piece.color+piece.type]:"vacía"} en ${squareName(square)}`} className={`relative aspect-square text-[clamp(28px,6vw,60px)] outline-none focus-visible:ring-4 focus-visible:ring-cyan-400 ${light?"bg-amber-100":"bg-amber-700"} ${selected===square?"ring-4 ring-inset ring-blue-500":""}`}>{piece?symbols[piece.color+piece.type]:""}{targets.has(square)&&<span className="absolute inset-[39%] rounded-full bg-emerald-500"/>}<small className="absolute bottom-1 left-1 text-[8px] opacity-60">{squareName(square)}</small></button>})}</div>}
function button(active:boolean){return`rounded-xl px-5 py-3 font-black ${active?"bg-slate-950 text-white":"border bg-white"}`}
