"use client";

import { useEffect, useMemo, useState } from "react";
import { agreeDraw, inCheck, initialState, legalMoves, makeMove, pgn, resign, squareName, type ChessState, type Color, type Move, type Promotion } from "./engine";
import { chessLessons, type ChessLevel, type ChessLesson } from "./lessons";

const symbols: Record<string,string>={wp:"♙",wn:"♘",wb:"♗",wr:"♖",wq:"♕",wk:"♔",bp:"♟",bn:"♞",bb:"♝",br:"♜",bq:"♛",bk:"♚"};
const pieceNames:Record<string,string>={p:"peón",n:"caballo",b:"alfil",r:"torre",q:"dama",k:"rey"};
const STORAGE="pem-ajedrez-desde-cero-v1";
type Saved={completed:string[];lessonSteps:Record<string,number>;lastActivity:string;currentLesson:string;game:ChessState|null;white:string;black:string};
const defaults:Saved={completed:[],lessonSteps:{},lastActivity:"",currentLesson:"board",game:null,white:"Blancas",black:"Negras"};

export default function ChessStudentApp(){
 const[saved,setSaved]=useState<Saved>(defaults),[tab,setTab]=useState<"learn"|"play">("learn"),[level,setLevel]=useState<ChessLevel>(1),[lesson,setLesson]=useState<ChessLesson>(chessLessons[0]),[state,setState]=useState<ChessState>(initialState),[history,setHistory]=useState<ChessState[]>([]),[selected,setSelected]=useState<number|null>(null),[pending,setPending]=useState<Move|null>(null),[flipped,setFlipped]=useState(false),[contrast,setContrast]=useState(false),[large,setLarge]=useState(false),[message,setMessage]=useState("Las blancas comienzan."),[drawOffer,setDrawOffer]=useState<Color|null>(null);
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(STORAGE)||"null") as Saved|null;if(value){const merged={...defaults,...value};setSaved(merged);if(merged.game)setState(merged.game);const found=chessLessons.find(x=>x.id===merged.currentLesson);if(found){setLesson(found);setLevel(found.level)}}}catch{}},[]);
 function persist(next:Saved){const value={...next,lastActivity:new Date().toISOString()};setSaved(value);try{localStorage.setItem(STORAGE,JSON.stringify(value))}catch{}void fetch("/api/students/chess/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)}).catch(()=>null);}
 useEffect(()=>{void fetch("/api/students/chess/progress").then(r=>r.ok?r.json():null).then(remote=>{if(remote?.progress&&(!saved.lastActivity||remote.progress.lastActivity>saved.lastActivity)){setSaved(remote.progress);if(remote.progress.game)setState(remote.progress.game)}}).catch(()=>null)},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const moves=useMemo(()=>selected===null?[]:legalMoves(state,selected),[state,selected]);
 const order=flipped?[...Array(64).keys()].reverse():[...Array(64).keys()];
 function choose(square:number){if(state.result!=="playing")return;const piece=state.board[square];if(selected===null){if(piece?.color===state.turn){setSelected(square);setMessage(`${pieceNames[piece.type]} ${piece.color==="w"?"blanco":"negro"} en ${squareName(square)} seleccionado.`)}return;}if(piece?.color===state.turn){setSelected(square);return;}const candidates=moves.filter(m=>m.to===square);if(!candidates.length){setSelected(null);setMessage("Movimiento no disponible.");return;}if(candidates.some(m=>m.promotion)){setPending(candidates[0]);return;}play(candidates[0]);}
 function play(move:Move,promotion?:Promotion){const next=makeMove(state,{...move,promotion});if(!next)return;setHistory(items=>[...items,state]);setState(next);setSelected(null);setPending(null);setDrawOffer(null);const status=describe(next);setMessage(status);persist({...saved,game:next,white:saved.white,black:saved.black});}
 function undo(){const previous=history.at(-1);if(!previous)return;setState(previous);setHistory(items=>items.slice(0,-1));setSelected(null);setMessage("Movimiento deshecho en modo aprendizaje.");persist({...saved,game:previous});}
 function newGame(){const next=initialState();setState(next);setHistory([]);setSelected(null);setDrawOffer(null);setMessage("Nueva partida. Las blancas comienzan.");persist({...saved,game:next});}
 function finish(next:ChessState,text:string){setHistory(items=>[...items,state]);setState(next);setMessage(text);persist({...saved,game:next});}
 function resetProgress(){if(!confirm("¿Reiniciar todas las lecciones y la partida guardada?"))return;try{localStorage.removeItem(STORAGE)}catch{}void fetch("/api/students/chess/progress",{method:"DELETE"}).catch(()=>null);setSaved(defaults);setState(initialState());setHistory([]);setLesson(chessLessons[0]);setLevel(1);setMessage("Progreso reiniciado.");}
 return <section className="space-y-6">
  <div className="rounded-[2rem] bg-gradient-to-br from-slate-950 via-slate-900 to-amber-800 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">♟ Escuela de estrategia · Acceso gratuito</p><h3 className="mt-2 text-3xl font-black sm:text-4xl">Ajedrez desde Cero</h3><p className="mt-2 max-w-2xl text-slate-200">Tres niveles: tablero, seis piezas, reglas completas y retos.</p></div><div className="rounded-2xl bg-white/10 px-5 py-3"><b>{saved.completed.length} de {chessLessons.length}</b><p className="text-xs text-slate-300">lecciones superadas</p></div></div></div>
  <div className="flex flex-wrap gap-3"><button type="button" onClick={()=>setTab("learn")} className={tabClass(tab==="learn")}>📘 Aprender</button><button type="button" onClick={()=>setTab("play")} className={tabClass(tab==="play")}>♟️ Partida reglamentaria</button><button type="button" onClick={()=>setContrast(v=>!v)} className="rounded-xl border px-4 py-2 font-bold">◐ Alto contraste</button><button type="button" onClick={()=>setLarge(v=>!v)} className="rounded-xl border px-4 py-2 font-bold">↔ Tamaño del tablero</button></div>
  {tab==="learn"?<Learning saved={saved} level={level} lesson={lesson} setLevel={setLevel} setLesson={x=>{setLesson(x);persist({...saved,currentLesson:x.id})}} persist={persist}/>:<div className="grid gap-6 xl:grid-cols-[minmax(420px,720px)_1fr]"><div><Board state={state} order={order} selected={selected} moves={moves} choose={choose} contrast={contrast} large={large}/><p aria-live="polite" className="mt-3 rounded-xl bg-blue-50 p-3 font-bold text-blue-950">{message}</p></div><aside className="space-y-4"><div className="rounded-2xl border bg-white p-5"><h4 className="text-xl font-black">Partida local</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Blancas<input value={saved.white} onChange={e=>{const value=e.target.value;setSaved(v=>({...v,white:value}))}} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Negras<input value={saved.black} onChange={e=>{const value=e.target.value;setSaved(v=>({...v,black:value}))}} className="mt-1 w-full rounded-lg border p-2"/></label></div><p className="mt-4 font-black">Turno: {state.turn==="w"?saved.white:saved.black}{inCheck(state,state.turn)&&state.result==="playing"?" · JAQUE":""}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={newGame} className="rounded-lg bg-slate-950 px-3 py-2 font-bold text-white">Nueva</button><button onClick={undo} disabled={!history.length} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Deshacer</button><button onClick={()=>setFlipped(v=>!v)} className="rounded-lg border px-3 py-2 font-bold">Girar</button></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setDrawOffer(state.turn)} disabled={state.result!=="playing"} className="rounded-lg border px-3 py-2 font-bold">Ofrecer tablas</button>{drawOffer&&<button onClick={()=>finish(agreeDraw(state),"Tablas por acuerdo.")} className="rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Aceptar tablas</button>}<button onClick={()=>finish(resign(state,state.turn),`${state.turn==="w"?saved.white:saved.black} abandona.`)} disabled={state.result!=="playing"} className="rounded-lg bg-red-700 px-3 py-2 font-bold text-white">Abandonar</button></div></div><div className="rounded-2xl border bg-white p-5"><h4 className="font-black">Registro algebraico</h4><p className="mt-2 min-h-12 text-sm leading-7">{state.san.map((m,i)=><span key={i} className="mr-2">{i%2===0?`${i/2+1}. `:""}{m}</span>)}</p><details className="mt-3"><summary className="cursor-pointer font-bold">Ver PGN</summary><pre className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-950 p-3 text-xs text-white">{pgn(state,saved.white,saved.black)}</pre></details></div><button onClick={resetProgress} className="rounded-xl border border-red-300 px-4 py-3 font-bold text-red-700">Reiniciar progreso</button></aside></div>}
  {pending&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="rounded-3xl bg-white p-6 text-center"><h4 className="text-xl font-black">Elige la promoción</h4><div className="mt-4 flex gap-3">{(["q","r","b","n"] as Promotion[]).map(type=><button key={type} onClick={()=>play(pending,type)} className="grid h-16 w-16 place-items-center rounded-xl bg-amber-100 text-4xl">{symbols[state.turn+type]}</button>)}</div></div></div>}
 </section>
}

function Learning({saved,level,lesson,setLevel,setLesson,persist}:{saved:Saved;level:ChessLevel;lesson:ChessLesson;setLevel:(x:ChessLevel)=>void;setLesson:(x:ChessLesson)=>void;persist:(x:Saved)=>void}){
 const step=saved.lessonSteps[lesson.id]||0,question=lesson.checks[Math.min(step,2)],complete=saved.completed.includes(lesson.id),lessons=chessLessons.filter(x=>x.level===level);
 function answer(index:number){if(index!==question.answer)return;const nextStep=Math.min(3,step+1),completed=nextStep===3?[...new Set([...saved.completed,lesson.id])]:saved.completed;persist({...saved,lessonSteps:{...saved.lessonSteps,[lesson.id]:nextStep},completed,currentLesson:lesson.id});}
 return <div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="rounded-3xl bg-slate-950 p-4 text-white"><div className="flex gap-2">{([1,2,3] as ChessLevel[]).map(x=><button key={x} onClick={()=>setLevel(x)} className={`rounded-lg px-3 py-2 text-sm font-black ${level===x?"bg-amber-400 text-slate-950":"bg-white/10"}`}>Nivel {x}</button>)}</div><div className="mt-4 grid gap-2">{lessons.map(x=><button key={x.id} onClick={()=>setLesson(x)} className={`rounded-xl p-3 text-left text-sm font-bold ${lesson.id===x.id?"bg-white text-slate-950":"bg-white/10"}`}>{saved.completed.includes(x.id)?"✓ ":""}{x.title}</button>)}</div></aside><article className="rounded-3xl border bg-white p-6 shadow-lg sm:p-8"><p className="text-xs font-black uppercase tracking-widest text-amber-700">Nivel {lesson.level} · {complete?"Superada":"Paso "+(step+1)+" de 3"}</p><h4 className="mt-2 text-3xl font-black">{lesson.title}</h4><p className="mt-4 text-lg leading-8 text-slate-700">{lesson.summary}</p>{complete?<div className="mt-6 rounded-2xl bg-emerald-100 p-5 font-black text-emerald-900">🏆 Lección superada con tres comprobaciones.</div>:<div className="mt-7"><h5 className="text-xl font-black">{question.question}</h5><div className="mt-4 grid gap-3 sm:grid-cols-3">{question.options.map((option,index)=><button key={option} onClick={()=>answer(index)} className="rounded-xl border-2 border-slate-200 p-4 font-bold hover:border-amber-500 hover:bg-amber-50">{option}</button>)}</div><p className="mt-3 text-sm text-slate-500">Debes completar tres comprobaciones diferentes para superar la lección.</p></div>}</article></div>
}

function Board({state,order,selected,moves,choose,contrast,large}:{state:ChessState;order:number[];selected:number|null;moves:Move[];choose:(x:number)=>void;contrast:boolean;large:boolean}){const targets=new Set(moves.map(m=>m.to));return <div role="grid" aria-label="Tablero de ajedrez" className={`grid grid-cols-8 overflow-hidden rounded-xl border-4 shadow-2xl ${large?"max-w-[760px]":"max-w-[620px]"}`}>{order.map(square=>{const piece=state.board[square],light=(Math.floor(square/8)+square%8)%2===0,isSelected=selected===square,isTarget=targets.has(square);return <button role="gridcell" aria-label={`${piece?`${pieceNames[piece.type]} ${piece.color==="w"?"blanco":"negro"}`:"casilla vacía"} en ${squareName(square)}`} aria-selected={isSelected} key={square} onClick={()=>choose(square)} className={`relative aspect-square text-[clamp(26px,6vw,58px)] leading-none outline-none focus-visible:ring-4 focus-visible:ring-cyan-400 ${contrast?(light?"bg-white":"bg-black"):(light?"bg-amber-100":"bg-amber-700")} ${isSelected?"ring-4 ring-inset ring-blue-500":""}`}>{piece?symbols[piece.color+piece.type]:""}{isTarget?<span aria-hidden="true" className={`absolute inset-[38%] rounded-full ${state.board[square]?"ring-4 ring-red-500":"bg-emerald-500"}`}/>:null}<span aria-hidden="true" className="absolute bottom-1 left-1 text-[9px] font-bold opacity-60">{squareName(square)}</span></button>})}</div>}
function tabClass(active:boolean){return`rounded-xl px-5 py-3 font-black ${active?"bg-slate-950 text-white":"border bg-white text-slate-800"}`}
function describe(state:ChessState){if(state.result==="checkmate")return`Jaque mate. Ganan ${state.winner==="w"?"las blancas":"las negras"}.`;if(state.result==="stalemate")return"Tablas por ahogado.";if(state.result==="draw-50")return"Tablas por la regla de 50 movimientos.";if(state.result==="draw-repetition")return"Tablas por triple repetición.";if(state.result==="draw-material")return"Tablas por material insuficiente.";return`${state.turn==="w"?"Turno de blancas":"Turno de negras"}${inCheck(state,state.turn)?". Jaque.":"."}`}
