export type ChessLevel = 1 | 2 | 3;
export interface ChessLesson { id: string; level: ChessLevel; title: string; summary: string; checks: Array<{ question: string; options: string[]; answer: number; feedback: string }> }

export const chessLessons: ChessLesson[] = [
  {id:"board",level:1,title:"El tablero y las coordenadas",summary:"El tablero tiene ocho columnas identificadas con letras, de la a a la h, y ocho filas identificadas con números, del 1 al 8.",checks:[{question:"¿Cómo se identifican las columnas?",options:["Con letras","Con números","Con colores"],answer:0,feedback:"Las columnas van de a a h."},{question:"¿Cuántas casillas tiene el tablero?",options:["32","64","81"],answer:1,feedback:"Ocho por ocho forman 64 casillas."},{question:"¿Qué color debe tener la esquina derecha cercana?",options:["Blanco","Negro","Cualquiera"],answer:0,feedback:"La casilla derecha cercana es clara."}]},
  {id:"setup",level:1,title:"Colocación inicial",summary:"Cada jugador comienza con 16 piezas. La dama se coloca en una casilla de su propio color.",checks:[{question:"¿Cuántos peones tiene cada lado?",options:["6","8","10"],answer:1,feedback:"Cada jugador comienza con ocho peones."},{question:"¿Dónde se coloca la dama blanca?",options:["d1","e1","a1"],answer:0,feedback:"La dama blanca ocupa d1."},{question:"¿Quién mueve primero?",options:["Negras","Blancas","Se sortea siempre"],answer:1,feedback:"Las blancas realizan el primer movimiento."}]},
  {id:"pawn",level:1,title:"El peón",summary:"Avanza de frente, captura en diagonal y puede avanzar dos casillas desde su posición inicial.",checks:[{question:"¿Cómo captura?",options:["De frente","En diagonal","Hacia atrás"],answer:1,feedback:"El peón captura una casilla diagonal hacia delante."},{question:"¿Puede retroceder?",options:["Sí","No"],answer:1,feedback:"El peón nunca retrocede."},{question:"¿Qué sucede al llegar al final?",options:["Desaparece","Se promociona","Vuelve al inicio"],answer:1,feedback:"Debe convertirse en dama, torre, alfil o caballo."}]},
  {id:"rook",level:1,title:"La torre",summary:"Se desplaza cualquier número de casillas por filas o columnas sin saltar piezas.",checks:[{question:"¿Puede moverse en diagonal?",options:["Sí","No"],answer:1,feedback:"La torre se mueve en línea recta."},{question:"¿Puede saltar piezas?",options:["Sí","No"],answer:1,feedback:"Ninguna pieza puede bloquear su recorrido."},{question:"¿Participa en un movimiento especial?",options:["Enroque","Captura al paso","Promoción"],answer:0,feedback:"La torre participa en el enroque."}]},
  {id:"bishop",level:1,title:"El alfil",summary:"Se desplaza por diagonales y permanece durante toda la partida en casillas del mismo color.",checks:[{question:"¿Por dónde se mueve?",options:["Diagonales","Filas","En L"],answer:0,feedback:"El alfil se desplaza diagonalmente."},{question:"¿Puede cambiar de color de casilla?",options:["Sí","No"],answer:1,feedback:"Cada alfil conserva el color de sus diagonales."},{question:"¿Puede saltar?",options:["Sí","No"],answer:1,feedback:"El alfil no salta piezas."}]},
  {id:"knight",level:1,title:"El caballo",summary:"Se mueve formando una L: dos casillas en una dirección y una perpendicular. Es la única pieza que salta.",checks:[{question:"¿Qué forma describe?",options:["L","Círculo","Diagonal larga"],answer:0,feedback:"Dos casillas y una perpendicular forman una L."},{question:"¿Puede saltar piezas?",options:["Sí","No"],answer:0,feedback:"Es la única pieza que puede saltar."},{question:"¿Puede ir de b1 a c3?",options:["Sí","No"],answer:0,feedback:"Ese es un movimiento válido de caballo."}]},
  {id:"queen",level:1,title:"La dama",summary:"Combina los movimientos de torre y alfil, pero no puede saltar piezas.",checks:[{question:"¿Se mueve en línea y diagonal?",options:["Sí","No"],answer:0,feedback:"La dama combina torre y alfil."},{question:"¿Puede saltar?",options:["Sí","No"],answer:1,feedback:"La dama no salta."},{question:"¿Es necesario arriesgarla al principio?",options:["Sí","No"],answer:1,feedback:"Conviene desarrollarla con prudencia."}]},
  {id:"king",level:1,title:"El rey",summary:"Se mueve una casilla en cualquier dirección y nunca puede quedar bajo ataque.",checks:[{question:"¿Cuántas casillas mueve normalmente?",options:["Una","Dos","Cualquiera"],answer:0,feedback:"Normalmente avanza una casilla."},{question:"¿Puede entrar en jaque?",options:["Sí","No"],answer:1,feedback:"Un movimiento que deja al propio rey atacado es ilegal."},{question:"¿Cuál es el objetivo?",options:["Capturarlo","Darle jaque mate","Llevarlo al centro"],answer:1,feedback:"La partida termina con el jaque mate, no capturando al rey."}]},
  {id:"turns",level:2,title:"Turnos y capturas",summary:"Las blancas comienzan y los turnos se alternan. Una captura ocupa la casilla de la pieza rival.",checks:[{question:"¿Se pueden saltar turnos?",options:["Sí","No"],answer:1,feedback:"Cada jugador debe realizar un movimiento legal."},{question:"¿Puedes ocupar una casilla propia?",options:["Sí","No"],answer:1,feedback:"No se puede capturar ni ocupar una pieza propia."},{question:"¿Se captura al rey?",options:["Sí","No"],answer:1,feedback:"El jaque mate termina antes de capturar al rey."}]},
  {id:"check",level:2,title:"Jaque y respuestas",summary:"Ante un jaque hay que mover el rey, capturar la pieza atacante o bloquear el ataque cuando sea posible.",checks:[{question:"¿Puedes ignorar un jaque?",options:["Sí","No"],answer:1,feedback:"Debes responder al jaque."},{question:"¿Bloquear siempre es posible?",options:["Sí","No"],answer:1,feedback:"No se bloquea un ataque de caballo o adyacente."},{question:"¿Una pieza clavada puede descubrir al rey?",options:["Sí","No"],answer:1,feedback:"No puede realizar un movimiento que exponga a su rey."}]},
  {id:"mate",level:2,title:"Jaque mate",summary:"El rey está atacado y no existe ninguna respuesta legal. La partida termina inmediatamente.",checks:[{question:"¿Mate significa rey capturado?",options:["Sí","No"],answer:1,feedback:"El rey no se captura."},{question:"¿Debe existir jaque?",options:["Sí","No"],answer:0,feedback:"Sin jaque y sin movimientos es ahogado."},{question:"¿Termina la partida?",options:["Sí","No"],answer:0,feedback:"El mate termina la partida."}]},
  {id:"stalemate",level:2,title:"Ahogado",summary:"El jugador no está en jaque, pero no tiene ningún movimiento legal. El resultado es tablas.",checks:[{question:"¿El rey está en jaque?",options:["Sí","No"],answer:1,feedback:"En el ahogado no hay jaque."},{question:"¿Tiene movimientos legales?",options:["Sí","No"],answer:1,feedback:"No existe movimiento legal."},{question:"¿Quién gana?",options:["Blancas","Negras","Nadie: tablas"],answer:2,feedback:"El ahogado produce tablas."}]},
  {id:"castle",level:2,title:"Enroque",summary:"El rey se desplaza dos casillas hacia una torre y esa torre pasa al otro lado del rey.",checks:[{question:"¿Puede enrocar un rey que ya se movió?",options:["Sí","No"],answer:1,feedback:"El derecho se pierde al mover el rey."},{question:"¿Puede atravesar jaque?",options:["Sí","No"],answer:1,feedback:"El rey no puede estar, cruzar ni terminar en jaque."},{question:"¿Debe estar libre el camino?",options:["Sí","No"],answer:0,feedback:"No debe haber piezas entre rey y torre."}]},
  {id:"en-passant",level:2,title:"Captura al paso",summary:"Un peón puede capturar inmediatamente a otro que acaba de avanzar dos casillas y quedó a su lado.",checks:[{question:"¿Se puede esperar un turno?",options:["Sí","No"],answer:1,feedback:"Solo es válida inmediatamente."},{question:"¿Qué pieza captura?",options:["Peón","Torre","Cualquiera"],answer:0,feedback:"Es una captura especial de peón."},{question:"¿El peón rival avanzó dos casillas?",options:["Sí","No"],answer:0,feedback:"Ese avance habilita la captura."}]},
  {id:"promotion",level:2,title:"Promoción",summary:"Al llegar a la última fila, el peón se convierte en dama, torre, alfil o caballo.",checks:[{question:"¿Solo puede elegirse dama?",options:["Sí","No"],answer:1,feedback:"Hay cuatro opciones."},{question:"¿Puede elegirse caballo?",options:["Sí","No"],answer:0,feedback:"El caballo es una promoción válida."},{question:"¿El efecto es inmediato?",options:["Sí","No"],answer:0,feedback:"La nueva pieza actúa inmediatamente."}]},
  {id:"draws",level:2,title:"Tipos de tablas",summary:"Puede haber tablas por acuerdo, ahogado, repetición, 50 movimientos o imposibilidad de mate.",checks:[{question:"¿Tres posiciones repetidas permiten tablas?",options:["Sí","No"],answer:0,feedback:"La triple repetición permite reclamar tablas."},{question:"¿Rey contra rey puede terminar en mate?",options:["Sí","No"],answer:1,feedback:"Es material insuficiente."},{question:"¿Puede acordarse tablas?",options:["Sí","No"],answer:0,feedback:"Los jugadores pueden acordarlas."}]},
  {id:"challenge-mate",level:3,title:"Reto: mate en una",summary:"Encuentra un movimiento que termine la partida.",checks:[{question:"¿Qué símbolo cierra una jugada de mate en notación?",options:["+","#","="],answer:1,feedback:"El signo # indica jaque mate."},{question:"¿Debes comprobar escapatorias?",options:["Sí","No"],answer:0,feedback:"Revisa movimientos, capturas y bloqueos."},{question:"¿Se captura al rey?",options:["Sí","No"],answer:1,feedback:"El mate termina antes."}]},
  {id:"challenge-safe",level:3,title:"Reto: captura segura",summary:"Compara atacantes y defensores antes de capturar.",checks:[{question:"¿Una captura siempre es buena?",options:["Sí","No"],answer:1,feedback:"Puede perder material o dejar al rey en peligro."},{question:"¿Debes revisar la respuesta rival?",options:["Sí","No"],answer:0,feedback:"Anticipa al menos una respuesta."},{question:"¿El valor material es el único criterio?",options:["Sí","No"],answer:1,feedback:"También importan seguridad, actividad y posición."}]},
  {id:"challenge-opening",level:3,title:"Reto: apertura sencilla",summary:"Controla el centro, desarrolla piezas y protege al rey.",checks:[{question:"¿Conviene mover la misma pieza muchas veces sin razón?",options:["Sí","No"],answer:1,feedback:"Desarrolla varias piezas."},{question:"¿Es útil enrocar?",options:["Sí","No"],answer:0,feedback:"Suele mejorar la seguridad del rey."},{question:"¿Conviene sacar la dama demasiado pronto?",options:["Sí","No"],answer:1,feedback:"Puede quedar expuesta a ataques con ganancia de tiempo."}]},
  {id:"challenge-protect",level:3,title:"Reto: protege al rey",summary:"Reconoce jaques y elige entre mover, capturar o bloquear.",checks:[{question:"¿Puedes responder moviendo otra pieza cualquiera?",options:["Sí","No"],answer:1,feedback:"La respuesta debe eliminar el jaque."},{question:"¿Puedes capturar al atacante?",options:["A veces","Nunca"],answer:0,feedback:"Solo cuando la captura es legal y deja seguro al rey."},{question:"¿El caballo se puede bloquear?",options:["Sí","No"],answer:1,feedback:"Su ataque no recorre casillas intermedias."}]},
  {id:"challenge-threat",level:3,title:"Reto: encuentra la pieza amenazada",summary:"Identifica ataques, defensores y posibles respuestas antes de perder material.",checks:[{question:"¿Una pieza atacada siempre debe moverse?",options:["Sí","No"],answer:1,feedback:"También puede defenderse, capturar o crear una amenaza mayor."},{question:"¿Hay que contar defensores?",options:["Sí","No"],answer:0,feedback:"Compara atacantes y defensores."},{question:"¿La seguridad del rey tiene prioridad?",options:["Sí","No"],answer:0,feedback:"Ninguna decisión puede dejar al rey en jaque."}]},
  {id:"challenge-queen-mate",level:3,title:"Reto: mate con dama y rey",summary:"Reduce el espacio del rey rival y acerca tu rey sin provocar ahogado.",checks:[{question:"¿La dama puede dar mate sola?",options:["Sí","No"],answer:1,feedback:"Necesita la protección del rey."},{question:"¿Debes reducir el espacio rival?",options:["Sí","No"],answer:0,feedback:"La dama crea una caja cada vez menor."},{question:"¿Debes vigilar el ahogado?",options:["Sí","No"],answer:0,feedback:"Conserva una casilla hasta preparar el mate."}]},
  {id:"challenge-rook-mate",level:3,title:"Reto: mate con torre y rey",summary:"Usa la torre para cortar filas o columnas y el rey para expulsar al rival.",checks:[{question:"¿La torre necesita ayuda del rey?",options:["Sí","No"],answer:0,feedback:"El rey controla las casillas de escape."},{question:"¿Conviene acercar la torre sin protección?",options:["Sí","No"],answer:1,feedback:"El rey rival podría capturarla."},{question:"¿La técnica reduce el espacio por franjas?",options:["Sí","No"],answer:0,feedback:"La torre corta una fila o columna."}]},
];
